.PHONY: clean All

All:
	@echo "----------Building project:[ DeclareClassAndObjects - Debug ]----------"
	@cd "Section13\DeclareClassAndObjects" && "$(MAKE)" -f  "DeclareClassAndObjects.mk"
clean:
	@echo "----------Cleaning project:[ DeclareClassAndObjects - Debug ]----------"
	@cd "Section13\DeclareClassAndObjects" && "$(MAKE)" -f  "DeclareClassAndObjects.mk" clean
