.PHONY: clean All

All:
	@echo "----------Building project:[ ProjectFromTemplate - Debug ]----------"
	@cd "ProjectFromTemplate" && "$(MAKE)" -f  "ProjectFromTemplate.mk"
clean:
	@echo "----------Cleaning project:[ ProjectFromTemplate - Debug ]----------"
	@cd "ProjectFromTemplate" && "$(MAKE)" -f  "ProjectFromTemplate.mk" clean
